# Generated by Django 5.0.4 on 2024-04-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beauticians',
            fields=[
                ('beauticianid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=100)),
                ('categoryimage', models.ImageField(upload_to='images/')),
                ('categorydescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('packageid', models.AutoField(primary_key=True, serialize=False)),
                ('packagename', models.CharField(max_length=50)),
                ('packagerate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PackageList',
            fields=[
                ('packagelistid', models.AutoField(primary_key=True, serialize=False)),
                ('packageid', models.IntegerField()),
                ('subcategoryid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('subcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryid', models.IntegerField()),
                ('subcategoryname', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
