# Generated by Django 5.0.4 on 2024-04-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagelist',
            old_name='subcategoryid',
            new_name='subcategoryname',
        ),
    ]
