# Generated by Django 5.0.4 on 2024-04-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_rename_subcategoryid_packagelist_subcategoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='subcategorydescription',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
