# Generated by Django 5.0.4 on 2024-04-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_packagebooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagebooking',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='packagebooking',
            old_name='last_name',
            new_name='phone',
        ),
    ]
