# Generated by Django 5.0.4 on 2024-05-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_packagebooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminuser',
            fields=[
                ('adminid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
