# Generated by Django 5.0.4 on 2024-05-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='adminame',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
