# Generated by Django 5.0.4 on 2024-07-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_rename_packagebooking_packagebookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageBookings',
            new_name='PackageBooking',
        ),
    ]
